import { AppBar, Button, FormControlLabel, IconButton, Switch, Toolbar, Typography } from '@material-ui/core'
import TextField from '@material-ui/core/TextField'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import MenuIcon from '@mui/icons-material/Menu';
import { GetServerSideProps } from 'next';
import { parseCookies } from 'nookies';
import { useContext } from 'react';
import { AuthContext } from '../contexts/authContext';

export default function Home() {
  const { user } = useContext(AuthContext);

  return (<>
    <AppBar position="static">
      <Toolbar variant="dense">
        <IconButton edge={'start'} color={'inherit'} aria-label="menu">
          <MenuIcon></MenuIcon>
        </IconButton>
        <Typography variant="h6" color="inherit" component="div">
          Must Do List - { user?.Name }
        </Typography>
      </Toolbar>
    </AppBar>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <TextField id="txtTitulo" label="Título" variant="standard" />
        <FormControlLabel control={<Switch></Switch>} label={`Finalizado`}></FormControlLabel>
        <Button variant={'contained'} color={'primary'}>Salvar</Button>
      </main>
    </div>
  </>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { ['mustdotoken-token']: token } = parseCookies(ctx);

  console.log(token);

  if (!token) {
    return {
      redirect: {
        destination: '/login',
        permanent: false
      }
    }
  }

  return { props: {} }
}