// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MustDoList.Data.Models
{
    [Table("todo")]
    [Index("UserId", Name = "FK_User")]
    public partial class Todo
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(500)]
        public string Title { get; set; }
        public bool Done { get; set; }
        public int UserId { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("Todos")]
        public virtual User User { get; set; }
    }
}